name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  show_welcoming:
    runs-on: ubuntu-latest
    steps:
    - name: show_text
      run: echo "Hello world"
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck

  job3:
    runs-on: ubuntu-latest
    steps:
    
    - needs:
        build
        show_welcoming
    - run: echo "job3 depnds on other two first to be executed"  
